FROM python:3.13-bookworm
WORKDIR /app

COPY requirements/backend.in .
RUN pip install -r backend.in

COPY . .

CMD ["python", "-m", "uvicorn", "spaceship.app:app", "--host", "0.0.0.0", "--port", "8000"]